### ISSUE TITLE
What is the cache Unit ? 

### ISSUE THREAD

**Issue by Doctor-Who** [3liz/docker-qgis-server#4]
Dear David,

I would like to know how is the CACHE unit for environment variable please :)

**Comment by dmarteau** [comment]
If you refer to the `QGSRV_CACHE_SIZE` environment variable: this is the maximum number of project  in the LRU cache.

**Comment by Doctor-Who** [comment]
Thanks for that information. I was thinking about Mb ou Gb limit. Not at all :)

**Comment by dmarteau** [comment]
Yes, there may be better name for the variable, this one  may lead to confusion.
