### ISSUE TITLE
Memory Leak ?

### ISSUE THREAD

**Issue by Doctor-Who** [3liz/docker-qgis-server#5]
Contact : 

Docker image deployed as : 
`docker run -d -p 8090:8080 --restart=unless-stopped --name "qgis-server-vhr" -v /data/raster/europe/vhr/2018:/projects -e QGSRV_SERVER_WORKERS=20 -e QGSRV_CACHE_ROOTDIR=/projects -e QGSRV_CACHE_SIZE=100 3liz/qgis-map-server:3.6`

- Docker version : 18.09.1_ce
- OS : openSUSE Leap 15.0
- 2 VHR images in COG format with pyramids ( 80 GB each) 

After 1 day using / teamwork around 10 person using QGIS 3.6:
![Screenshot_20190517_174118](https://user-images.githubusercontent.com/5890416/57940022-e65c1780-78cb-11e9-926e-55f228c70cb8.png)

After restarting Docker image :
![Screenshot_20190517_174150](https://user-images.githubusercontent.com/5890416/57940051-f542ca00-78cb-11e9-95c8-c3d5925b3ff7.png)

It seems even when all client are closed and webservice unused, memory does not increase but memory is not purged.

Although, it displays very fast / good performance

**Comment by dmarteau** [comment]
Hi,

Thx for your feedback,

The server keep project's layers in a LRU cache, rasters are managed with gdal that use also a cache of its own. As a consequence, memory may grow up to the cache limits. At the moment, it is not expected that this memory to be released.  

It is also good to know that each workers are independent processes and manage their own cache - and cache is not shared among workers.

It would be interesting to watch the memory consumption and see if its continue to increase  up to the container limit, in this case we may face a Qgis memory leak problem that will have to be addressed.

**Comment by Doctor-Who** [comment]
Thanks for quick answered 
I will add variable to limit CPU and Memory Limit of the container and see what's happen.
I will let you know test results asap.
