### ISSUE TITLE
Failure to run the image and accessing ows services

### ISSUE THREAD

**Issue by NyakudyaA** [3liz/docker-qgis-server#7]
# Problem

I have been trying to use this image to serve out my qgis projects but have largely been unsuccessful. Maybe I am doing a schoolboy error.

I ran 
```
docker run -p 8080:8080 \
       -v `pwd`projects-qgis3:/projects \
       -e QGSRV_SERVER_WORKERS=2 \
       -e QGSRV_LOGGING_LEVEL=DEBUG  \
       -e QGSRV_CACHE_ROOTDIR=/projects \
       -e QGSRV_CACHE_SIZE=10 \
       3liz/qgis-map-server:3.6
```
where the contets of `projects-qgis3` directory looks like
![contents](https://user-images.githubusercontent.com/2510900/58538003-7cf5d600-81f4-11e9-80c9-7df36b28a74c.png)

And when I run the `http://localhost:8080/ows/?SERVICE=WMS&VERSION=1.1.0&REQUEST=GetCapabilities` I get the following error.
![get](https://user-images.githubusercontent.com/2510900/58538110-b4fd1900-81f4-11e9-85df-5bf427de7f5d.png)

If I add the map parameter to the  request I get the following error.
![map-request](https://user-images.githubusercontent.com/2510900/58538188-dfe76d00-81f4-11e9-82fb-6426fb37c0e4.png)

But If I exec into the container I can see that the `project.qgs` does exist in `/projects/`

![data-cont](https://user-images.githubusercontent.com/2510900/58538337-33f25180-81f5-11e9-808f-b61b6f31bd67.png)

But If I use my qgis project with another image it works without any problem ie
![run](https://user-images.githubusercontent.com/2510900/58538627-d1e61c00-81f5-11e9-99a2-8ea419f64cdf.png)

Which results in the following request
![get-req](https://user-images.githubusercontent.com/2510900/58538680-f17d4480-81f5-11e9-9231-b27e9bed685b.png)

So I am quite sure the qgis project has no errors but I am puzzled to what I am doing wrong here

**Comment by dmarteau** [comment]
Your MAP path is incorrect: path must be relative to the QGSRV_CACHE_ROOTDIR i.e:
```
?MAP=project.qgs&...
```
not
```
?MAP=/project/project.qgs&...
```

Absolute project paths are forbidden because this is a security hole.

**Comment by NyakudyaA** [comment]
Thanks will try it out

**Comment by NyakudyaA** [comment]
Works
